### ISSUE TITLE
conflicting declaration

### ISSUE THREAD

**Issue by jreilley** [cbpowell/ESPSense#4]
While trying to setup ESPSense via ESPHome that is already working with HomeAssistant, I get the following error.  It looks like ESPAsyncUDP is not compatible with wifi_component; or at least not with the default versions.  I could use some assistance resolving this error.

...
Compiling /data/espsense-main/.pioenvs/espsense-main/src/main.cpp.o
Generating partitions /data/espsense-main/.pioenvs/espsense-main/partitions.bin
In file included from src/espsense.h:3:0,
                 from src/main.cpp:41:
/data/espsense-main/.piolibdeps/espsense-main/ESPAsyncUDP/src/ESPAsyncUDP.h:19:25: error: conflicting declaration 'typedef struct ip4_addr ip_addr_t'
 typedef struct ip4_addr ip_addr_t;
                         ^
In file included from /root/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/tcpip_adapter/tcpip_adapter.h:24:0,
                 from /root/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp32/esp_event_legacy.h:23,
                 from /root/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp_event/esp_event.h:26,
                 from /root/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/esp32/esp_wifi.h:64,
                 from src/esphome/components/wifi/wifi_component.h:11,
                 from src/esphome.h:30,
                 from src/main.cpp:3:
/root/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/lwip/lwip/ip_addr.h:76:3: note: previous declaration as 'typedef struct ip_addr ip_addr_t'
 } ip_addr_t;
   ^
Compiling /data/espsense-main/.pioenvs/espsense-main/lib0f4/AsyncTCP-esphome/AsyncTCP.cpp.o
*** [/data/espsense-main/.pioenvs/espsense-main/src/main.cpp.o] Error 1
========================= [FAILED] Took 24.36 seconds =========================

**Comment by cbpowell** [comment]
To summarize some side channel conversation and debugging between @jreilley and myself, this issue was caused by:
1. ESPSense was not compatible with ESP32 units because of the use of the ESPAsyncUDP library which is ESP8266-specific. However, it can use the core AsyncUDP library on ESP32 without issue. I added a switch based on the build arch in a3d688dae4382f0cbcae6429d1cb30faf0676baa.
2. I hadn't set the setup priority for the custom component, which apparently resulted in ESPSense trying to listen on UDP before the wifi connection was ready, which in turn prevented wifi from connecting! I configured the setup priority to AFTER_WIFI in 68754b018f01020c3bbcc1d428b3b0a9173ed85c.

The last thing that I need to do is update the docs (relative to item 1) to note that for an ESP8266 board you need to specify the ESPAsyncUDP library in your YAML config, but do NOT need to when using an ESP32 board.

**Comment by cbpowell** [comment]
Fixed in release 0.2.1 - thanks for the help figuring this one out @jreilley!
